import { DataTable, StatusPill } from "../../components/data-table";
import { PageHeader } from "../../components/page-header";
import { StatCard } from "../../components/stat-card";
import { damaApi } from "../../lib/api-client";
import type { ContentAsset } from "../../lib/types";

async function loadContentAssets(): Promise<ContentAsset[]> {
  try {
    return await damaApi.contentAssets();
  } catch {
    return [];
  }
}

export default async function ContentAssetsPage() {
  const assets = await loadContentAssets();

  return (
    <main className="page-shell">
      <PageHeader
        eyebrow="Content Assets"
        title="Content asset library"
        lead="Browse manual and AI-generated content assets stored inside DAMA."
      >
        <div className="actions">
          <a href="/content-assets/new">Create content asset</a>
          <a href="/search/content-assets">Search assets</a>
        </div>
      </PageHeader>

      <section className="stats-grid">
        <StatCard label="Assets" value={assets.length} helper="Total loaded assets" />
        <StatCard
          label="AI Generated"
          value={assets.filter((asset) => asset.source === "ai_generated").length}
          helper="Generated by AI workflows"
        />
        <StatCard
          label="Manual"
          value={assets.filter((asset) => asset.source === "manual").length}
          helper="Manual content records"
        />
        <StatCard
          label="Types"
          value={new Set(assets.map((asset) => asset.content_type)).size}
          helper="Unique content types"
        />
      </section>

      <section className="panel">
        <div className="panel-heading">
          <p className="eyebrow">Library</p>
          <h2>All content assets</h2>
        </div>

        <DataTable<ContentAsset>
          emptyLabel="No content assets found."
          items={assets}
          columns={[
            {
              key: "title",
              label: "Title",
              render: (asset) => (
                <a className="table-link" href={`/content-assets/${asset.id}`}>
                  {asset.title}
                </a>
              )
            },
            {
              key: "content_type",
              label: "Type",
              render: (asset) => asset.content_type
            },
            {
              key: "source",
              label: "Source",
              render: (asset) => asset.source
            },
            {
              key: "status",
              label: "Status",
              render: (asset) => <StatusPill status={asset.status} />
            }
          ]}
        />
      </section>
    </main>
  );
}
