from pathlib import Path

ROOT = Path("I:/DAMA")

(ROOT / "frontend/next-env.d.ts").write_text(
    """/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is required by Next.js TypeScript projects.
// Do not edit this file manually unless updating Next.js TypeScript setup.
""",
    encoding="utf-8",
)

(ROOT / "frontend/tsconfig.json").write_text(
    """{
  "compilerOptions": {
    "target": "ES2017",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": false,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "types": ["node", "react", "react-dom"],
    "plugins": [
      {
        "name": "next"
      }
    ]
  },
  "include": [
    "next-env.d.ts",
    ".next/types/**/*.ts",
    "**/*.ts",
    "**/*.tsx"
  ],
  "exclude": ["node_modules"]
}
""",
    encoding="utf-8",
)

print("Next TypeScript env hotfix applied.")
